apiVersion: apps/v1
kind: Deployment

metadata:
  name: hell-cli

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hell-cli

  template:
    metadata:
      labels:
        app: hell-cli

    spec:
      containers:
      - name: hell-cli
        image: 340257301941.dkr.ecr.us-east-1.amazonaws.com/hell-cli:latest
        ports:
        - containerPort: 80
